#ifndef _EXPLOSION_BEHAVIOR_H
#define _EXPLOSION_BEHAVIOR_H

enum class EXPLOSION_BEHAVIOR {
    DEFER_TO_DATA = -1,
    NOT_EXPLOSIVE,
    EXPLODE_ON_IMPACT,
    EXPLODE_ON_DECAY_AND_IMPACT
};

#endif