#ifndef _ENTITY_TYPE_ID
#define _ENTITY_TYPE_ID

enum ENTITY_SAVE_ID {
    NO_SAVE,
    DROPPED_ITEM,
    PROJECTILE,
    ORBITER,
    CACTOID,
    PLANTMAN,
    SNOWMAN,
    FROG,
    TURTLE,
    PENGUIN,
    PLAYER,
    YETI,
    DOG,
    SKELETON,
    SHARK,
    CYCLOPS,
    CHEESE_BOSS,
    FLESH_CHICKEN,
    CANNON_BOSS,
    LOG_MONSTER,
    BOULDER_BEAST,
    TULIP_MONSTER,
    TREE_BOSS,
    CREAM_BOSS,
    CHEF_BOSS,
    BURGER_BEAST,
    BOMB_BOY,
    MEGA_BOMB_BOY,
    BABY_BOSS,
    SOLDIER,
    BIG_SNOWMAN,
    BEE_FAMILIAR
};

#endif